version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_BTC_RPC_EXPLORER_IP
      APP_PORT: $APP_BTC_RPC_EXPLORER_PORT

  web:
    image: getumbrel/btc-rpc-explorer:v2.0.2
    restart: on-failure
    stop_grace_period: 1m
    environment:
      # Bitcoin Core
      BTCEXP_BITCOIND_HOST: $APP_BITCOIN_NODE_IP
      BTCEXP_BITCOIND_PORT: $APP_BITCOIN_RPC_PORT
      BTCEXP_BITCOIND_USER: $APP_BITCOIN_RPC_USER
      BTCEXP_BITCOIND_PASS: $APP_BITCOIN_RPC_PASS
      
      # Electrum
      BTCEXP_ELECTRUMX_SERVERS: "tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT"

      # Docker requirements
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_ADDRESS_API: electrumx
      # Log level
      DEBUG: "btcexp:*,electrumClient"
      # Performance
      BTCEXP_SLOW_DEVICE_MODE: "true"
      BTCEXP_NO_INMEMORY_RPC_CACHE: "true"
      # Privacy
      BTCEXP_PRIVACY_MODE: "true"
      BTCEXP_NO_RATES: "true"
      # Disable RPC
      BTCEXP_RPC_ALLOWALL: "false"
      BTCEXP_BASIC_AUTH_PASSWORD: ""
    networks:
      default:
        ipv4_address: $APP_BTC_RPC_EXPLORER_IP
